More testing with a forced failure for ffmpeg

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -47,20 +47,21 @@ jobs:
           if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
       
       - name: Setup FFmpeg
-        id: setup_ffmpeg
+        # id: setup_ffmpeg
+        continue-on-error: true
         uses: FedericoCarboni/setup-ffmpeg@v1-beta
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       
       - name: BACKUP - Setup ffmpeg and ffprobe
-        id: backup_setup_ffmpeg
-        if: steps.setup_ffmpeg.outcome == 'failure'
+        # id: backup_setup_ffmpeg
+        # if: steps.setup_ffmpeg.outcome == 'failure'
         run: |
           python ffmpeg_setup.py
           echo "./bin" >> $GITHUB_PATH
       
       - name: Run unit tests.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m unittest discover -v -s ./tests/unit_tests -p "*_tests.py"
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -69,11 +70,11 @@ jobs:
           S3_BUCKET: ${{ secrets.S3_BUCKET }}
 
       - name: Run integration tests - MainWindow.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m unittest -v tests.integration_tests.main_window_tests
       
       - name: Run integration tests - SetupWindow.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m tests.integration_tests.setup_window_tests
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -81,7 +82,7 @@ jobs:
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
 
       - name: Run integration tests - SetupWindow UI.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m tests.integration_tests.setup_window_ui_elements_tests
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -89,11 +90,11 @@ jobs:
           AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
       
       - name: Run integration tests - UpdateDatabaseWindow.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m unittest -v tests.integration_tests.update_database_window_tests
 
       - name: Run integration tests - MassUploadWindow.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m unittest -v tests.integration_tests.mass_upload_window_tests
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -102,7 +103,7 @@ jobs:
           S3_BUCKET: ${{ secrets.S3_BUCKET }}
 
       - name: Run integration tests - MassUploadWindow UI.
-        if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
+        # if: steps.setup_ffmpeg.outcome == 'success' || (steps.setup_ffmpeg.outcome == 'failure' && steps.backup_setup_ffmpeg.outcome == 'success')
         run: python -m unittest -v tests.integration_tests.mass_upload_window_ui_elements_tests
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
